In [18]:
import pandas as pd
import matplotlib.pyplot as plt
import pickle
#from pandas_profiling import ProfileReport
import numpy as np

In [25]:
pip install pandas-profiling

  Using cached https://files.pythonhosted.org/packages/57/b7/e13216265ae3135ecda13e966aad9ce04b7e7b3e2d87d056b032fc9f457c/pandas_profiling-3.2.0-py2.py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/bb/ee/59a884d5ee3c0fbf47c0e449daf87388809dafb48152c045873235851355/matplotlib-3.5.2-cp37-cp37m-win_amd64.whl
  Using cached https://files.pythonhosted.org/packages/bc/c3/f068337a370801f372f2f8f6bad74a5c140f6fda3d9de154052708dd3c65/Jinja2-3.1.2-py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/b2/56/f886ed6f1777ffa9d54c6e80231b69db8a1f52dcc33f5967b06a105dcfe0/pandas-1.3.5-cp37-cp37m-win_amd64.whl
  Using cached https://files.pythonhosted.org/packages/21/b2/0067e1ea3d0d7fcbd76e9fb58bd4aa2dd194ab23c251984a1a722bbf1dd0/pydantic-1.9.1-cp37-cp37m-win_amd64.whl
  Using cached https://files.pythonhosted.org/packages/8a/c4/d15f1e627fff25443ded77ea70a7b5532d6371498f9285d44d62587e209c/tqdm-4.64.0-py2.py3-none-any.whl
  Using cached https://files.pythonhosted

scipy 1.7.3 has requirement numpy<1.23.0,>=1.16.5, but you'll have numpy 1.16.2 which is incompatible.
pandas 1.3.5 has requirement numpy>=1.17.3; platform_machine != "aarch64" and platform_machine != "arm64" and python_version < "3.10", but you'll have numpy 1.16.2 which is incompatible.
matplotlib 3.5.2 has requirement numpy>=1.17, but you'll have numpy 1.16.2 which is incompatible.
phik 0.12.2 has requirement numpy>=1.18.0, but you'll have numpy 1.16.2 which is incompatible.
Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'c:\\users\\lenovo\\anaconda3\\lib\\site-packages\\~atplotlib\\backends\\_backend_agg.cp37-win_amd64.pyd'
Consider using the `--user` option or check the permissions.



In [45]:
#from pandas_profiling import ProfileReport

In [31]:
df = pd.read_csv('D:\\1neuron\\2-Machine Learning\\Introduction to Machine Learning\\1-Linear Regression\\Data\\Advertising.csv')

In [32]:
df

TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
5      8.7   48.9       75.0    7.2
6     57.5   32.8       23.5   11.8
7    120.2   19.6       11.6   13.2
8      8.6    2.1        1.0    4.8
9    199.8    2.6       21.2   15.6
10    66.1    5.8       24.2   12.6
11   214.7   24.0        4.0   17.4
12    23.8   35.1       65.9    9.2
13    97.5    7.6        7.2   13.7
14   204.1   32.9       46.0   19.0
15   195.4   47.7       52.9   22.4
16    67.8   36.6      114.0   12.5
17   281.4   39.6       55.8   24.4
18    69.2   20.5       18.3   11.3
19   147.3   23.9       19.1   14.6
20   218.4   27.7       53.4   18.0
21   237.4    5.1       23.5   17.5
22    13.2   15.9       49.6    5.6
23   228.3   16.9       26.2   20.5
24    62.3   12.6       18.3    9.7
25   262.9    3.5       19.5   17.0
26   142.9   29.3       12.6   15.0
27   240.1   16.7       22.9   20.9
28   248.8   27.1       22.9   18.9
29    70.6   16.0       40.8   10.5
..     ...    ...        ...    ...
170   50.0   11.6       18.4    8.4
171  164.5   20.9       47.4   17.5
172   19.6   20.1       17.0    7.6
173  168.4    7.1       12.8   16.7
174  222.4    3.4       13.1   16.5
175  276.9   48.9       41.8   27.0
176  248.4   30.2       20.3   20.2
177  170.2    7.8       35.2   16.7
178  276.7    2.3       23.7   16.8
179  165.6   10.0       17.6   17.6
180  156.6    2.6        8.3   15.5
181  218.5    5.4       27.4   17.2
182   56.2    5.7       29.7    8.7
183  287.6   43.0       71.8   26.2
184  253.8   21.3       30.0   17.6
185  205.0   45.1       19.6   22.6
186  139.5    2.1       26.6   10.3
187  191.1   28.7       18.2   17.3
188  286.0   13.9        3.7   20.9
189   18.7   12.1       23.4    6.7
190   39.5   41.1        5.8   10.8
191   75.5   10.8        6.0   11.9
192   17.2    4.1       31.6    5.9
193  166.8   42.0        3.6   19.6
194  149.7   35.6        6.0   17.3
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

In [33]:
df.head(10)

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9
5    8.7   48.9       75.0    7.2
6   57.5   32.8       23.5   11.8
7  120.2   19.6       11.6   13.2
8    8.6    2.1        1.0    4.8
9  199.8    2.6       21.2   15.6

In [34]:
df.tail()

TV  Radio  Newspaper  Sales
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

In [35]:
df.describe()

TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   15.130500
std     85.854236   14.846809   21.778621    5.283892
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   11.000000
50%    149.750000   22.900000   25.750000   16.000000
75%    218.825000   36.525000   45.100000   19.050000
max    296.400000   49.600000  114.000000   27.000000

In [44]:
#ProfileReport(df)

In [11]:
pf = ProfileReport(df)

In [13]:
pf.to_widgets()

In [43]:
df

TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
5      8.7   48.9       75.0    7.2
6     57.5   32.8       23.5   11.8
7    120.2   19.6       11.6   13.2
8      8.6    2.1        1.0    4.8
9    199.8    2.6       21.2   15.6
10    66.1    5.8       24.2   12.6
11   214.7   24.0        4.0   17.4
12    23.8   35.1       65.9    9.2
13    97.5    7.6        7.2   13.7
14   204.1   32.9       46.0   19.0
15   195.4   47.7       52.9   22.4
16    67.8   36.6      114.0   12.5
17   281.4   39.6       55.8   24.4
18    69.2   20.5       18.3   11.3
19   147.3   23.9       19.1   14.6
20   218.4   27.7       53.4   18.0
21   237.4    5.1       23.5   17.5
22    13.2   15.9       49.6    5.6
23   228.3   16.9       26.2   20.5
24    62.3   12.6       18.3    9.7
25   262.9    3.5       19.5   17.0
26   142.9   29.3       12.6   15.0
27   240.1   16.7       22.9   20.9
28   248.8   27.1       22.9   18.9
29    70.6   16.0       40.8   10.5
..     ...    ...        ...    ...
170   50.0   11.6       18.4    8.4
171  164.5   20.9       47.4   17.5
172   19.6   20.1       17.0    7.6
173  168.4    7.1       12.8   16.7
174  222.4    3.4       13.1   16.5
175  276.9   48.9       41.8   27.0
176  248.4   30.2       20.3   20.2
177  170.2    7.8       35.2   16.7
178  276.7    2.3       23.7   16.8
179  165.6   10.0       17.6   17.6
180  156.6    2.6        8.3   15.5
181  218.5    5.4       27.4   17.2
182   56.2    5.7       29.7    8.7
183  287.6   43.0       71.8   26.2
184  253.8   21.3       30.0   17.6
185  205.0   45.1       19.6   22.6
186  139.5    2.1       26.6   10.3
187  191.1   28.7       18.2   17.3
188  286.0   13.9        3.7   20.9
189   18.7   12.1       23.4    6.7
190   39.5   41.1        5.8   10.8
191   75.5   10.8        6.0   11.9
192   17.2    4.1       31.6    5.9
193  166.8   42.0        3.6   19.6
194  149.7   35.6        6.0   17.3
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

In [15]:
pf.to_file('test.html')

In [36]:
df

TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
5      8.7   48.9       75.0    7.2
6     57.5   32.8       23.5   11.8
7    120.2   19.6       11.6   13.2
8      8.6    2.1        1.0    4.8
9    199.8    2.6       21.2   15.6
10    66.1    5.8       24.2   12.6
11   214.7   24.0        4.0   17.4
12    23.8   35.1       65.9    9.2
13    97.5    7.6        7.2   13.7
14   204.1   32.9       46.0   19.0
15   195.4   47.7       52.9   22.4
16    67.8   36.6      114.0   12.5
17   281.4   39.6       55.8   24.4
18    69.2   20.5       18.3   11.3
19   147.3   23.9       19.1   14.6
20   218.4   27.7       53.4   18.0
21   237.4    5.1       23.5   17.5
22    13.2   15.9       49.6    5.6
23   228.3   16.9       26.2   20.5
24    62.3   12.6       18.3    9.7
25   262.9    3.5       19.5   17.0
26   142.9   29.3       12.6   15.0
27   240.1   16.7       22.9   20.9
28   248.8   27.1       22.9   18.9
29    70.6   16.0       40.8   10.5
..     ...    ...        ...    ...
170   50.0   11.6       18.4    8.4
171  164.5   20.9       47.4   17.5
172   19.6   20.1       17.0    7.6
173  168.4    7.1       12.8   16.7
174  222.4    3.4       13.1   16.5
175  276.9   48.9       41.8   27.0
176  248.4   30.2       20.3   20.2
177  170.2    7.8       35.2   16.7
178  276.7    2.3       23.7   16.8
179  165.6   10.0       17.6   17.6
180  156.6    2.6        8.3   15.5
181  218.5    5.4       27.4   17.2
182   56.2    5.7       29.7    8.7
183  287.6   43.0       71.8   26.2
184  253.8   21.3       30.0   17.6
185  205.0   45.1       19.6   22.6
186  139.5    2.1       26.6   10.3
187  191.1   28.7       18.2   17.3
188  286.0   13.9        3.7   20.9
189   18.7   12.1       23.4    6.7
190   39.5   41.1        5.8   10.8
191   75.5   10.8        6.0   11.9
192   17.2    4.1       31.6    5.9
193  166.8   42.0        3.6   19.6
194  149.7   35.6        6.0   17.3
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

In [63]:
x = df[["TV"]]
x

TV
0    230.1
1     44.5
2     17.2
3    151.5
4    180.8
5      8.7
6     57.5
7    120.2
8      8.6
9    199.8
10    66.1
11   214.7
12    23.8
13    97.5
14   204.1
15   195.4
16    67.8
17   281.4
18    69.2
19   147.3
20   218.4
21   237.4
22    13.2
23   228.3
24    62.3
25   262.9
26   142.9
27   240.1
28   248.8
29    70.6
..     ...
170   50.0
171  164.5
172   19.6
173  168.4
174  222.4
175  276.9
176  248.4
177  170.2
178  276.7
179  165.6
180  156.6
181  218.5
182   56.2
183  287.6
184  253.8
185  205.0
186  139.5
187  191.1
188  286.0
189   18.7
190   39.5
191   75.5
192   17.2
193  166.8
194  149.7
195   38.2
196   94.2
197  177.0
198  283.6
199  232.1

[200 rows x 1 columns]

In [51]:
y = df.Sales

In [76]:
y

Sales
0     22.1
1     10.4
2     12.0
3     16.5
4     17.9
5      7.2
6     11.8
7     13.2
8      4.8
9     15.6
10    12.6
11    17.4
12     9.2
13    13.7
14    19.0
15    22.4
16    12.5
17    24.4
18    11.3
19    14.6
20    18.0
21    17.5
22     5.6
23    20.5
24     9.7
25    17.0
26    15.0
27    20.9
28    18.9
29    10.5
..     ...
170    8.4
171   17.5
172    7.6
173   16.7
174   16.5
175   27.0
176   20.2
177   16.7
178   16.8
179   17.6
180   15.5
181   17.2
182    8.7
183   26.2
184   17.6
185   22.6
186   10.3
187   17.3
188   20.9
189    6.7
190   10.8
191   11.9
192    5.9
193   19.6
194   17.3
195    7.6
196   14.0
197   14.8
198   25.5
199   18.4

[200 rows x 1 columns]

In [77]:
#y = y.to_frame()


In [79]:
from sklearn.linear_model import LinearRegression
linear = LinearRegression()

In [81]:
linear.fit(x,y)

LinearRegression()

In [84]:
linear.intercept_

array([6.97482149])

In [85]:
linear.coef_

array([[0.05546477]])

In [86]:
file = 'linear_reg.sav'
pickle.dump(linear,open(file,'wb'))


In [87]:
linear.predict([[45]])

array([[9.47073616]])

In [89]:
l = [4,5,6,7,89,34,45,67,23]

In [90]:
for i in l :
    print(i, "--->",linear.predict([[i]]))

4 ---> [[7.19668057]]
5 ---> [[7.25214534]]
6 ---> [[7.30761011]]
7 ---> [[7.36307488]]
89 ---> [[11.91118606]]
34 ---> [[8.86062368]]
45 ---> [[9.47073616]]
67 ---> [[10.69096111]]
23 ---> [[8.25051121]]


In [92]:
m = 0
b = 0

learning_rate = 0.001
for i in range(len(x)):
    x1 = x.iloc[0,:].values[0]
    y1 = y.iloc[0,:].values[0]
    guess = m * x1 + b
    error = y1 - guess
    m -= error * x1 * learning_rate
    b -= error * learning_rate
    print(i,"-->",error)


0 --> 22.1
1 --> 1192.228921
2 --> 64317.18552347621
3 --> 3469719.850606826
4 --> 187181011.47788498
5 --> 10097855898.007576
6 --> 544749133108.3736
7 --> 29387586931288.76
8 --> 1585372446058103.8
9 --> 8.552610320122098e+16
10 --> 4.613877544657299e+18
11 --> 2.4890489804040274e+20
12 --> 1.3427675023634585e+22
13 --> 7.243829187767652e+23
14 --> 3.907829256307933e+25
15 --> 2.1081570396833663e+27
16 --> 1.1372876890136895e+29
17 --> 6.135327033209838e+30
18 --> 3.309825488138415e+32
19 --> 1.7855518870685798e+34
20 --> 9.632518550720752e+35
21 --> 5.196455745809179e+37
22 --> 2.8033325008372525e+39
23 --> 1.5123140645599226e+41
24 --> 8.158482196395479e+42
25 --> 4.401257206337689e+44
26 --> 2.374346665228713e+46
27 --> 1.2808890329256004e+48
28 --> 6.910013346812769e+49
29 --> 3.7277455912064194e+51
30 --> 2.0110072868626858e+53
31 --> 1.0848783021445417e+55
32 --> 5.852594061457461e+56
33 --> 3.157299503593863e+58
34 --> 1.7032686789337312e+60
35 --> 9.18862524551248e+61
36 --> 

C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: RuntimeWarning: overflow encountered in double_scalars
  # Remove the CWD from sys.path while we load stuff.


In [97]:
def gd(x,y,n):
    m=6
    c=3
    alpha=0.8
    len=x.shape[0]
    for r in range(n):
        y_pred=m*x +c
        cost=(1/len)*((y_pred-y)**2).sum()
        print('cost is ',cost)
        m=m-(-alpha/len)*((y-y_pred)*x).sum()
        c=c-(-alpha/len)*((y-y_pred).sum())
        print('m,c is',m,c)
        if cost<1:
            plt.scatter(x,y)
            plt.plot(x,y_pred)


In [ ]:
file = 'linear_reg.sav'
pickle.dump(linear,open(file,'wb'))

In [45]:
saved_model = pickle.load(open(file,'rb'))

In [46]:
saved_model.predict([[45]])

array([9.17174237])

In [98]:
linear.score(x,y)

0.8121757029987414